// src/ui/RDFTable/RDFTermDisplay.tsx
import { styled } from "@mui/joy";
import type { Term } from "@rdfjs/types";
import { Link } from "@tanstack/react-router";
import { HoverTermCard } from "./HoverTermCard";

interface RDFTermDisplayProps {
  term?: Term;
}

export function RDFTermDisplay({ term }: RDFTermDisplayProps) {
  if (term?.termType === "NamedNode")
    return (
      <HoverTermCard term={term}>
        <Term>
          <Link to="/term/$termId" params={{ termId: term.value }}>
            {term.value}
          </Link>
        </Term>
      </HoverTermCard>
    );

  if (term?.termType === "BlankNode")
    return <Term className="blanknode">{term.value}</Term>;

  if (term?.termType === "Literal")
    return (
      <Term>
        {term.value}
        {term.language.length > 0 && (
          <span className="lang">{term.language}</span>
        )}
        {term.datatype.value !==
          "http://www.w3.org/1999/02/22-rdf-syntax-ns#langString" && (
          <DataType>^^{term.datatype.value}</DataType>
        )}
      </Term>
    );

  return <Term>{term?.value}</Term>;
}

const Term = styled("span")`
  font-size: small;

  & .blanknode {
    color: gray;
  }

  & .lang {
    color: gray;
    font-size: x-small;
  }
`;

const DataType = styled("span")`
  color: gray;
  font-size: x-small;
`;

// src/components/RDFTermDisplay.vue
<script setup lang="ts">
import type { Term } from '@rdfjs/types'

defineProps<{
  term?: Term
}>()
</script>

<template>
  <span class="term" v-if="term?.termType === 'NamedNode'"
    ><a :href="term.value" target="_blank">{{ term.value }}</a></span
  ><span class="term blanknode" v-else-if="term?.termType === 'BlankNode'">{{ term.value }}</span>
  <span class="term" v-else-if="term?.termType === 'Literal'"
    >{{ term.value }}<span class="lang" v-if="term.language.length > 0">@{{ term.language }}</span
    ><span
      class="datatype"
      v-if="term.datatype.value !== 'http://www.w3.org/1999/02/22-rdf-syntax-ns#langString'"
      >^^{{ term.datatype.value }}</span
    ></span
  >
  <span class="term" v-else>{{ term?.value }}</span>
</template>

<style scoped>
.term {
  font-size: small;
}
.blanknode {
  color: gray;
}
.lang {
  color: gray;
  font-size: x-small;
}
.datatype {
  color: gray;
  font-size: x-small;
}
</style>
