// src/components/Query.vue
<script setup lang="ts">
import { queryProvivderKey } from '@/stores/query'
import { type Source } from '@/modules/sources'
import Yasqe from '@triply/yasqe'
import { inject, ref, onMounted, computed } from 'vue';

const DEFAULT_QUERY = `\
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT * WHERE {
  ?sub ?pred ?obj .
} LIMIT 10\
`;

let {
  sources,
  selectedSources,
  currentSparql,
  running,
  executeQuery,
  stopQuery,
} = inject(queryProvivderKey)!;

const notReadyToRun = computed(() => 
  selectedSources.value.length < 1 || currentSparql.value.trim().length < 1
);

const onSourceSelectionChange = (nextSelection: { source: Source; selected: boolean }[]) => {
  sources.value.forEach((currentSource) => {
    if (nextSelection.includes(currentSource)) {
      currentSource.selected = true;
    } else {
      currentSource.selected = false;
    }
  });
}

const getSourceName = (source: { source: Source; selected: boolean }): string => {
  return source.source.name
}

const editorElement = ref(null);
onMounted(() => {
  if (editorElement.value !== null) {
    const previous = globalThis.yasqe?.getValue();
    globalThis.yasqe = new Yasqe(editorElement.value);
    if (previous) globalThis.yasqe.setValue(previous);
    currentSparql.value = globalThis.yasqe.getValue();
    globalThis.yasqe.on('change', () => {
      if (globalThis.yasqe !== null) currentSparql.value = globalThis.yasqe.getValue()
    });
    if (currentSparql.value === "") globalThis.yasqe.setValue(DEFAULT_QUERY);
  }
});

const popover = ref();
const togglePopover = (event: any) => { popover.value.toggle(event); }
</script>

<template>
  <div class="flex">
    <div class="label-container">
      <h3>Sources</h3>
      <MultiSelect
        :modelValue="selectedSources"
        @update:modelValue="onSourceSelectionChange"
        :options="sources"
        :maxSelectedLabels="3"
        class="multiselect"
        :optionLabel="getSourceName"
        placeholder="Select Sources"
        :pt="{
          header: { style: { display: 'none' } },
          listContainer: { style: { maxHeight: 'none' } }
        }"
      />
    </div>

    <div class="label-container query">
      <h3>SPARQL Query</h3>
      <div ref="editorElement" class="editor-wrapper"></div>
    </div>

    <div class="buttons">
      <Button
        label="Save Query"
        @click="togglePopover"
        severity="secondary"
        icon="pi pi-bookmark"
        iconPos="right"
        size="small"
      />

      <Button
        v-if="!running"
        label="Run Query"
        @click="executeQuery"
        :disabled="notReadyToRun"
        v-tooltip="
          notReadyToRun
            ?  'Please provide a SPARQL query and at least one source.'
            : undefined
        "
        icon="pi pi-arrow-right"
        iconPos="right"
        size="small"
      />
      <Button
        v-else
        label="Stop Query"
        @click="stopQuery"
        severity="danger"
        icon="pi pi-stop"
        iconPos="right"
        size="small"
      />
    </div>
  </div>

  <Popover ref="popover">
    <div :style="{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }">
      <InputText placeholder="Name" />
      <div class="save-buttons" :style="{ display: 'flex', gap: '0.5rem', justifyContent: 'flex-end' }">
        <Button label="Cancel" @click="togglePopover" severity="secondary" size="small" :style="{flex: '1'}" />
        <Button label="Save" size="small" icon="pi pi-bookmark-fill" iconPos="right" :style="{flex: '1'}" />
      </div>
    </div>
  </Popover>
</template>

<style scoped>
.flex {
  height: 100%;
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.multiselect {
  width: 100%;
}

.label-container {
  display: flex;
  flex-direction: column;
}

.label-container.query {
  flex: 1;
  display: flex;
  flex-direction: column;

  /*
  By default this is auto, we have to set it to 0 so that it can be
  smaller than its content. This is important for the .editor-wrapper
  to overflow properly.
  */
  min-height: 0px;
}

.label-container > h3 {
  margin: 0px;
  font-size: 1rem;
  font-weight: 500;
  margin-bottom: 6px;
}

.editor-wrapper {
  flex: 1;
  overflow-y: auto;
}

.buttons {
  display: flex;
  flex-direction: row;
  justify-content: flex-end;
  gap: 1rem;
}
</style>

// src/ui/Panels/Query.tsx
import { ArrowForwardRounded, SaveRounded, Stop } from "@mui/icons-material";
import { Button, ButtonGroup, styled } from "@mui/joy";
import { SourceSelect } from "../SourceSelect";
import { YasqeEditor } from "../YasqeEditor";
import { useEffect, useMemo, useState } from "react";
import { getRouteApi } from "@tanstack/react-router";
import { useDebounce } from "@uidotdev/usehooks";
import { useQueryContext } from "../../context/query";
import { SaveQueryDialog } from "../SaveQueryDialog";

const rootRouteApi = getRouteApi("__root__");
const indexRouteApi = getRouteApi("/");

export function Query() {
  const { sources } = rootRouteApi.useLoaderData();
  const searchParams = indexRouteApi.useSearch();
  const navigate = indexRouteApi.useNavigate();

  const { runQuery, stopQuery, running } = useQueryContext()!;

  const [saveQueryDialogOpen, setSaveQueryDialogOpen] = useState(false);

  const [isSparqlValid, setIsSparqlValid] = useState(true);
  const [fastUpdatingSparql, setFastUpdatingSparql] = useState(
    searchParams.query,
  );
  const debouncedSparql = useDebounce(fastUpdatingSparql, 250);

  useEffect(() => {
    navigate({
      search: (prev) => ({ ...prev, query: debouncedSparql }),
      replace: true,
    });
    localStorage.setItem("sparql-query", debouncedSparql);
  }, [debouncedSparql, navigate]);

  useEffect(() => {
    setFastUpdatingSparql(searchParams.query);
  }, [searchParams.query]);

  const selectedSources = useMemo(
    () => sources.filter((s) => searchParams.sources.includes(s.shortname)),
    [searchParams, sources],
  );

  return (
    <Wrapper>
      <LabelContainer>
        <h3>Sources</h3>
        <SourceSelect />
      </LabelContainer>

      <LabelContainer className="query">
        <h3>SPARQL Query</h3>
        <YasqeEditor
          value={fastUpdatingSparql}
          onChange={(newValue, isSyntaxValid) => {
            setFastUpdatingSparql(newValue);
            setIsSparqlValid(isSyntaxValid);
          }}
        />
      </LabelContainer>

      <ButtonsContainer>
        <ButtonGroup>
          <Button
            color={"neutral"}
            variant={"outlined"}
            endDecorator={<SaveRounded />}
            onClick={() => setSaveQueryDialogOpen(true)}
          >
            Save Query
          </Button>
          {running ? (
            <Button
              color={"danger"}
              variant={"solid"}
              endDecorator={<Stop />}
              onClick={stopQuery}
            >
              Stop Query
            </Button>
          ) : (
            <Button
              color={"primary"}
              variant={"solid"}
              endDecorator={<ArrowForwardRounded />}
              disabled={!isSparqlValid || selectedSources.length < 1}
              onClick={() => {
                runQuery(searchParams.query, selectedSources);
              }}
            >
              Run Query
            </Button>
          )}
        </ButtonGroup>
      </ButtonsContainer>

      <SaveQueryDialog
        open={saveQueryDialogOpen}
        setOpen={setSaveQueryDialogOpen}
        query={fastUpdatingSparql}
        sources={selectedSources.map((s) => s.shortname)}
      />
    </Wrapper>
  );
}

const Wrapper = styled("div")`
  height: 100%;
  display: flex;
  flex-direction: column;
  gap: 1rem;
`;

const LabelContainer = styled("div")`
  display: flex;
  flex-direction: column;

  &.query {
    flex: 1;
    display: flex;
    flex-direction: column;

    /*
    By default this is auto, we have to set it to 0 so that it can be
    smaller than its content. This is important for the .editor-wrapper
    to overflow properly.
    */
    min-height: 0px;
  }

  & > h3 {
    margin: 0px;
    font-size: 1rem;
    font-weight: 500;
    margin-bottom: 6px;
  }
`;

const ButtonsContainer = styled("div")`
  display: flex;
  flex-direction: row;
  justify-content: flex-end;
  gap: 1rem;
`;
